[package]
name = "lerest"
version = "0.0.1"
authors = ["Hadi Hidayat Hammurabi <hadihammurabi@gmail.com>"]
edition = "2018"

[dependencies]
gio="0.9.0"

[dependencies.gtk]
version = "0.9.0"
features = ["v3_16"]

[dependencies.reqwest]
version = "0.11.3"
features = ["blocking"]
