[package]
name = "lerest"
version = "0.0.1"
authors = ["Hadi Hidayat Hammurabi <hadihammurabi@gmail.com>"]
edition = "2018"

[dependencies]
gio="0.9.0"
ureq="2.1.1"

[dependencies.gtk]
version = "0.9.0"
features = ["v3_16"]
